"""create itineraries table

Revision ID: 159f76bc0325
Revises: 90ffaca0a5b1
Create Date: 2026-08-23 10:45:32.526530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159f76bc0325'
down_revision: Union[str, Sequence[str], None] = '90ffaca0a5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itineraries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='行程ID'),
    sa.Column('conversation_id', sa.String(length=32), nullable=False, comment='来源会话ID（12位hex）'),
    sa.Column('plan', sa.JSON(), nullable=False, comment='行程计划 JSON（ItineraryPlan：destination/days/daily_plans/tips 等）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间（北京时间）'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间（北京时间），保存后再次编辑时自动刷新'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itineraries_conversation_id'), 'itineraries', ['conversation_id'], unique=False)
    # 注：autogenerate 顺带检测到 ix_users_username（models.User.username 声明了 index=True），
    #     但那是与「创建 itineraries 表」无关的既有状态，不在本次迁移范围内，已剔除。
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itineraries_conversation_id'), table_name='itineraries')
    op.drop_table('itineraries')
    # ### end Alembic commands ###
