"""add message_count to conversation

Revision ID: 16e730f08f15
Revises: 6d4a9e02f185
Create Date: 2026-08-27 15:36:30.762668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e730f08f15'
down_revision: Union[str, Sequence[str], None] = '6d4a9e02f185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('message_count', sa.Integer(), nullable=False,server_default="1", comment='会话消息数'))
    op.execute(
    "UPDATE conversations SET message_count = 1"
)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('conversations', 'message_count')
    # ### end Alembic commands ###
