"""add rbac audit log and token usage calls

Revision ID: 187ae9229b33
Revises: 1d940c550538
Create Date: 2026-09-16 22:37:55.553168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '187ae9229b33'
down_revision: Union[str, Sequence[str], None] = '1d940c550538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('operator_id', sa.Integer(), nullable=False, comment='操作者用户ID'),
    sa.Column('operator_email', sa.String(length=50), nullable=False, comment='操作者邮箱（冗余存一份，便于追溯）'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='动作标识，如 user.role.update / user.status.update'),
    sa.Column('target_type', sa.String(length=32), nullable=False, comment='目标类型，如 user'),
    sa.Column('target_id', sa.String(length=64), nullable=False, comment='目标标识（用户ID等，字符串存储以兼容多种主键）'),
    sa.Column('detail', sa.Text(), nullable=True, comment='变更明细（JSON 字符串：改前/改后）'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='来源 IP'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='操作时间（UTC）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_log_action'), 'admin_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_created_at'), 'admin_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_operator_id'), 'admin_audit_log', ['operator_id'], unique=False)

    # 以下三列都加在「已有数据」的表上。SQLite 给已有表添加 NOT NULL 列时
    # 必须提供 server_default 填充既有行，否则迁移直接失败（user 表已有 39 行）。
    # 语义上这正是我们想要的回填：既有用户一律为普通用户且启用；
    # 历史用量行的调用次数无从得知，记为 0。
    op.add_column(
        'token_usage',
        sa.Column('calls', sa.Integer(), nullable=False, server_default='0',
                  comment='LLM 调用次数'),
    )
    op.create_index(op.f('ix_token_usage_model'), 'token_usage', ['model'], unique=False)
    op.create_index(op.f('ix_token_usage_record_date'), 'token_usage', ['record_date'], unique=False)
    op.add_column(
        'users',
        sa.Column('role', sa.String(length=16), nullable=False, server_default='user',
                  comment='角色：user=普通用户，admin=管理员（管理端接口的鉴权依据）'),
    )
    op.add_column(
        'users',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true(),
                  comment='是否启用：被禁用的用户无法登录，但数据保留'),
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_token_usage_record_date'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_model'), table_name='token_usage')
    op.drop_column('token_usage', 'calls')
    op.drop_index(op.f('ix_admin_audit_log_operator_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_created_at'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
