"""add itinerary shares

Revision ID: a028db63a514
Revises: 187ae9229b33
Create Date: 2026-09-16 22:50:49.580407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a028db63a514'
down_revision: Union[str, Sequence[str], None] = '187ae9229b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('itinerary_id', sa.Integer(), nullable=False, comment='被分享的行程ID（行程删除时级联删除分享）'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='分享创建者ID（冗余记录，便于按用户批量查询与撤销）'),
    sa.Column('token', sa.String(length=64), nullable=False, comment='分享令牌（URL 安全随机串）'),
    sa.Column('allow_copy', sa.Boolean(), nullable=False, comment='是否允许访问者复制行程到自己的账号'),
    sa.Column('allow_edit', sa.Boolean(), nullable=False, comment='是否允许访问者直接编辑行程'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='访问密码哈希（argon2）；为空表示无需密码'),
    sa.Column('password_plain', sa.String(length=64), nullable=True, comment='访问密码明文（便于分享者再次查看）'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间（UTC）；为空表示永不过期'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='撤销时间（UTC）；非空表示已失效'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='访问次数'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间（UTC）'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_shares_expires_at'), 'itinerary_shares', ['expires_at'], unique=False)
    op.create_index(op.f('ix_itinerary_shares_itinerary_id'), 'itinerary_shares', ['itinerary_id'], unique=False)
    op.create_index(op.f('ix_itinerary_shares_owner_id'), 'itinerary_shares', ['owner_id'], unique=False)
    op.create_index(op.f('ix_itinerary_shares_token'), 'itinerary_shares', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itinerary_shares_token'), table_name='itinerary_shares')
    op.drop_index(op.f('ix_itinerary_shares_owner_id'), table_name='itinerary_shares')
    op.drop_index(op.f('ix_itinerary_shares_itinerary_id'), table_name='itinerary_shares')
    op.drop_index(op.f('ix_itinerary_shares_expires_at'), table_name='itinerary_shares')
    op.drop_table('itinerary_shares')
    # ### end Alembic commands ###
