"""init schema (PostgreSQL)

Revision ID: a222c2af2cbd
Revises: 
Create Date: 2026-09-18 19:34:19.910447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a222c2af2cbd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('operator_id', sa.Integer(), nullable=False, comment='操作者用户ID'),
    sa.Column('operator_email', sa.String(length=50), nullable=False, comment='操作者邮箱（冗余存一份，便于追溯）'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='动作标识，如 user.role.update / user.status.update'),
    sa.Column('target_type', sa.String(length=32), nullable=False, comment='目标类型，如 user'),
    sa.Column('target_id', sa.String(length=64), nullable=False, comment='目标标识（用户ID等，字符串存储以兼容多种主键）'),
    sa.Column('detail', sa.Text(), nullable=True, comment='变更明细（JSON 字符串：改前/改后）'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='来源 IP'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='操作时间（UTC）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_log_action'), 'admin_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_created_at'), 'admin_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_operator_id'), 'admin_audit_log', ['operator_id'], unique=False)
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('model', sa.String(length=50), nullable=False, comment='模型 ID'),
    sa.Column('input_tokens', sa.Integer(), nullable=False, comment='输入 token 数'),
    sa.Column('output_tokens', sa.Integer(), nullable=False, comment='输出 token 数'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='总 token 数'),
    sa.Column('calls', sa.Integer(), nullable=False, comment='LLM 调用次数'),
    sa.Column('record_date', sa.String(length=10), nullable=False, comment='统计日期 yyyy-MM-dd（本地时区）'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model', 'record_date', name='uq_model_date')
    )
    op.create_index(op.f('ix_token_usage_model'), 'token_usage', ['model'], unique=False)
    op.create_index(op.f('ix_token_usage_record_date'), 'token_usage', ['record_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('email', sa.String(length=50), nullable=False, comment='用户邮箱'),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False, comment='角色：user=普通用户，admin=管理员（管理端接口的鉴权依据）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用：被禁用的用户无法登录，但数据保留'),
    sa.Column('avatar', sa.String(length=255), nullable=False, comment='头像文件名（不含域名，如 photographer.png）'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间（UTC）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=32), nullable=False, comment='会话ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='会话标题'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='会话创建时间（UTC）'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='会话消息数'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('user_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID（用户注销时级联删除记忆）'),
    sa.Column('fact_key', sa.String(length=64), nullable=False, comment='事实键：标量属性如 budget_level/home_city；多值偏好用 preference 等'),
    sa.Column('fact_value', sa.String(length=255), nullable=False, comment='事实取值（字符串统一表示，便于比较与展示）'),
    sa.Column('previous_value', sa.String(length=255), nullable=True, comment='被本次覆盖的旧值（仅标量键会用到），便于追溯偏好变化'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='置信度 0-1：用户明确表述取高值，模型推断取低值'),
    sa.Column('evidence', sa.String(length=500), nullable=True, comment='来源原文片段，便于人工核对提炼是否准确'),
    sa.Column('source_conversation_id', sa.String(length=32), nullable=True, comment='来源会话ID；会话删除后置空但记忆保留'),
    sa.Column('hit_count', sa.Integer(), nullable=False, comment='被重复提取到的次数，越高说明越稳定'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否生效：用户可停用某条记忆而无需删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='首次提取时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='最近一次提取/修改时间（UTC）'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fact_key', 'fact_value', name='uq_user_memory_fact')
    )
    op.create_index(op.f('ix_user_memories_fact_key'), 'user_memories', ['fact_key'], unique=False)
    op.create_index(op.f('ix_user_memories_is_active'), 'user_memories', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    op.create_table('itineraries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='行程ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID（行程独立归属用户，删除用户时级联删除）'),
    sa.Column('conversation_id', sa.String(length=32), nullable=True, comment='来源会话ID（12位hex）；会话删除后置空，行程保留'),
    sa.Column('plan', sa.JSON(), nullable=False, comment='行程计划 JSON（ItineraryPlan：destination/days/daily_plans/tips 等）'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间（UTC），保存后再次编辑时自动刷新'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itineraries_conversation_id'), 'itineraries', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_itineraries_user_id'), 'itineraries', ['user_id'], unique=False)
    op.create_table('itinerary_shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('itinerary_id', sa.Integer(), nullable=False, comment='被分享的行程ID（行程删除时级联删除分享）'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='分享创建者ID（冗余记录，便于按用户批量查询与撤销）'),
    sa.Column('token', sa.String(length=64), nullable=False, comment='分享令牌（URL 安全随机串）'),
    sa.Column('allow_copy', sa.Boolean(), nullable=False, comment='是否允许访问者复制行程到自己的账号'),
    sa.Column('allow_edit', sa.Boolean(), nullable=False, comment='是否允许访问者直接编辑行程'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='访问密码哈希（argon2）；为空表示无需密码'),
    sa.Column('password_plain', sa.String(length=64), nullable=True, comment='访问密码明文（便于分享者再次查看）'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间（UTC）；为空表示永不过期'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='撤销时间（UTC）；非空表示已失效'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='访问次数'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间（UTC）'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_shares_expires_at'), 'itinerary_shares', ['expires_at'], unique=False)
    op.create_index(op.f('ix_itinerary_shares_itinerary_id'), 'itinerary_shares', ['itinerary_id'], unique=False)
    op.create_index(op.f('ix_itinerary_shares_owner_id'), 'itinerary_shares', ['owner_id'], unique=False)
    op.create_index(op.f('ix_itinerary_shares_token'), 'itinerary_shares', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itinerary_shares_token'), table_name='itinerary_shares')
    op.drop_index(op.f('ix_itinerary_shares_owner_id'), table_name='itinerary_shares')
    op.drop_index(op.f('ix_itinerary_shares_itinerary_id'), table_name='itinerary_shares')
    op.drop_index(op.f('ix_itinerary_shares_expires_at'), table_name='itinerary_shares')
    op.drop_table('itinerary_shares')
    op.drop_index(op.f('ix_itineraries_user_id'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_conversation_id'), table_name='itineraries')
    op.drop_table('itineraries')
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_is_active'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_fact_key'), table_name='user_memories')
    op.drop_table('user_memories')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_usage_record_date'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_model'), table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index(op.f('ix_admin_audit_log_operator_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_created_at'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
