"""add user memories

Revision ID: c390d0140a2a
Revises: a028db63a514
Create Date: 2026-09-16 23:02:22.394271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c390d0140a2a'
down_revision: Union[str, Sequence[str], None] = 'a028db63a514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID（用户注销时级联删除记忆）'),
    sa.Column('fact_key', sa.String(length=64), nullable=False, comment='事实键：标量属性如 budget_level/home_city；多值偏好用 preference 等'),
    sa.Column('fact_value', sa.String(length=255), nullable=False, comment='事实取值（字符串统一表示，便于比较与展示）'),
    sa.Column('previous_value', sa.String(length=255), nullable=True, comment='被本次覆盖的旧值（仅标量键会用到），便于追溯偏好变化'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='置信度 0-1：用户明确表述取高值，模型推断取低值'),
    sa.Column('evidence', sa.String(length=500), nullable=True, comment='来源原文片段，便于人工核对提炼是否准确'),
    sa.Column('source_conversation_id', sa.String(length=32), nullable=True, comment='来源会话ID；会话删除后置空但记忆保留'),
    sa.Column('hit_count', sa.Integer(), nullable=False, comment='被重复提取到的次数，越高说明越稳定'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否生效：用户可停用某条记忆而无需删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='首次提取时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='最近一次提取/修改时间（UTC）'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fact_key', 'fact_value', name='uq_user_memory_fact')
    )
    op.create_index(op.f('ix_user_memories_fact_key'), 'user_memories', ['fact_key'], unique=False)
    op.create_index(op.f('ix_user_memories_is_active'), 'user_memories', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_is_active'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_fact_key'), table_name='user_memories')
    op.drop_table('user_memories')
    # ### end Alembic commands ###
