"""init users and conversations

Revision ID: d7f8f759a074
Revises: 
Create Date: 2026-08-17 16:29:54.062627

"""
# ── 迁移脚本 = 一次“表结构变更记录”（类似一次 git commit）────────
# 每个迁移文件都有 upgrade(升级) 和 downgrade(回滚) 两个函数：
#   upgrade   : 把表结构从旧版改成新版（真正建表/改表）
#   downgrade : 回滚到上一版（撤销这次变更）
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f8f759a074'        # 本迁移的唯一 ID（类似 commit hash）
down_revision: Union[str, Sequence[str], None] = None
# ↑ down_revision 指向前一个迁移的 ID。None 表示这是“第一个迁移”(基线)。
# 这是 Alembic 串起版本链的依据：通过它知道谁先谁后。
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 这些是 `--autogenerate` 自动生成的建表语句，等于手写 CREATE TABLE。
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # create_index: 给 users.username 建唯一索引（对应模型里 index=True + unique=True）
    op.create_table('conversations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 回滚：和 upgrade 相反，先删 index 再删表（顺序要和建表相反）
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
